// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIUQSgh_7QKTcDYj7Z4goHBLt5NtijRoI',
    appId: '1:398555808166:web:85f8d210b653a2bddbcf67',
    messagingSenderId: '398555808166',
    projectId: 'dameyu-f9f2e',
    authDomain: 'dameyu-f9f2e.firebaseapp.com',
    storageBucket: 'dameyu-f9f2e.appspot.com',
    measurementId: 'G-H1MNR8ESMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_gFoGJVDio3dCD9TFW6LtPB-1TCMsSDw',
    appId: '1:398555808166:android:99a34d48ddbe4d38dbcf67',
    messagingSenderId: '398555808166',
    projectId: 'dameyu-f9f2e',
    storageBucket: 'dameyu-f9f2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdCAIWXWwHvt6JQOTzp-7IRKyhm_ZgaTE',
    appId: '1:398555808166:ios:64ec722069af5f72dbcf67',
    messagingSenderId: '398555808166',
    projectId: 'dameyu-f9f2e',
    storageBucket: 'dameyu-f9f2e.appspot.com',
    iosBundleId: 'com.example.dameyu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdCAIWXWwHvt6JQOTzp-7IRKyhm_ZgaTE',
    appId: '1:398555808166:ios:64ec722069af5f72dbcf67',
    messagingSenderId: '398555808166',
    projectId: 'dameyu-f9f2e',
    storageBucket: 'dameyu-f9f2e.appspot.com',
    iosBundleId: 'com.example.dameyu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIUQSgh_7QKTcDYj7Z4goHBLt5NtijRoI',
    appId: '1:398555808166:web:4095ccbed77d552edbcf67',
    messagingSenderId: '398555808166',
    projectId: 'dameyu-f9f2e',
    authDomain: 'dameyu-f9f2e.firebaseapp.com',
    storageBucket: 'dameyu-f9f2e.appspot.com',
    measurementId: 'G-PKKMDFQKL7',
  );
}
